name: Update README.md and docs/ TOC

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/README.md"
      - "docs/*.md"

permissions:
  contents: write

jobs:
  update_toc:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - uses: technote-space/toc-generator@9e238e7974de5fcf7b17b7acc54c896160dda0a3 # v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_PATHS: README.md,docs/*.md,*/README.md
